#!/bin/bash

function create_user(){
  useradd -p $(openssl passwd -1 $USER) $USER
}

#Magic "cd to script directory" command
cd "${0%/*}"

USER=executioner
NAME=executionerd
INSTALL_DIR=/usr/bin

#Create a new user if it doesn't exist
id -u $USER >/dev/null || create_user

chmod -R o+w .

su $USER -c "pyinstaller -Fn $NAME main.py"

cp dist/$NAME $INSTALL_DIR
cp init/$NAME.conf /etc/init

chmod +x $INSTALL_DIR/$NAME

mkdir /var/log/$USER &>/dev/null
chown $USER /var/log/$USER
chgrp $USER /var/log/$USER

mkdir /var/local/$USER &>/dev/null
chown $USER /var/local/$USER
chgrp $USER /var/local/$USER

initctl reload-configuration

chmod -R o-w .
