#!/bin/bash

function create_user(){
  useradd -p $(openssl passwd -1 $USER) $USER
}

#Magic "cd to script directory" command
cd "${0%/*}"

USER=executioner
NAME=executioner
MANAGERNAME=executioner-manager
INSTALL_DIR=/usr/bin

#Create a new user if it doesn't exist
id -u $USER >/dev/null || create_user

chmod -R go+w .

su $USER -c "pyinstaller -Fn $NAME main.py"

cp dist/$NAME $INSTALL_DIR
#cp init.d/$NAME /etc/init.d
cp systemd/$MANAGERNAME $INSTALL_DIR
cp systemd/$NAME.service /etc/systemd/system

chmod +x $INSTALL_DIR/$NAME
chmod +x init.d/$NAME /etc/init.d

mkdir /var/log/$USER &>/dev/null
chown $USER /var/log/$USER
chgrp $USER /var/log/$USER
chmod g+ws /var/log/$USER
setfacl -Rm default:g::rw /var/log/$USER

mkdir /var/local/$USER &>/dev/null
echo 0 >/var/local/$USER/top_switch
echo 0 >/var/local/$USER/bottom_switch
chown -R $USER /var/local/$USER
chgrp -R $USER /var/local/$USER

#update-rc.d -f $NAME defaults

systemctl enable $NAME.service

chmod -R go-w .
